### ISSUE TITLE
Fail tests if docker-compose up fails

### ISSUE THREAD

**Issue by alunduil** [racker/torment#35]
If docker-compose up throws an error we should either skip or fail that particular test.   My vote is failure.  What does everyone else think?

**Comment by dubsquared** [comment]
For consistency sake, I would say fail on the first failed test.

**Comment by alunduil** [comment]
What would this be consistent with?  We don't have anything like this currently.  Controlling when to break out of nose is a nose idea.  We're just talking about whether the test will result in a failure or skip status.
